In [1]:
import numpy as np
import pandas as pd

In [2]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0                 30          0         2    1                          4  
1                 31          0         1    0                          0  
2                 31          0         0    0                          2  
3                 24          0         2    0                          4  
4                 30          0         2    1                          2  
..               ...        ...       ...  ...                        ...  
695               22          1         2    0                          8  
696               24          0         1    2                          3  
697               25          1         0    0                          8  
698               25          1         0    0                          2  
699               25          0         1    1                          2  

[700 rows x 15 columns]

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>3,1,0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Absenteeism Time in Hours']=targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          1  
1               31          0         1    0                          0  
2               31          0         0    0                          0  
3               24          0         2    0                          1  
4               30          0         2    1                          0

In [9]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week','Daily Work Load Average','Distance to Work'],axis=1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                     289   33               30          0         2    1  
1                     118   50               31          0         1    0  
2                     179   38               31          0         0    0  
3                     279   39               24          0         2    0  
4                     289   33               30          0         2    1

In [13]:
data_with_targets.shape

(700, 11)

In [14]:
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                       289   33               30          0         2    1  
1                       118   50               31          0         1    0  
2                       179   38               31          0         0    0  
3                       279   39               24          0         2    0  
4                       289   33               30          0         2    1  
..                      ...  ...              ...        ...       ...  ...  
695                     179   40               22          1         2    0  
696                     225   28               24          0         1    2  
697                     330   28               25          1         0    0  
698                     235   32               25          1         0    0  
699                     291   40               25          0         1    1  

[700 rows x 11 columns]

In [15]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  
0                       289   33               30          0         2  
1                       118   50               31          0         1  
2                       179   38               31          0         0  
3                       279   39               24          0         2  
4                       289   33               30          0         2  
..                      ...  ...              ...        ...       ...  
695                     179   40               22          1         2  
696                     225   28               24          0         1  
697                     330   28               25          1         0  
698                     235   32               25          1         0  
699                     291   40               25          0         1  

[700 rows x 10 columns]

In [16]:
unscaled_inputs=data_with_targets.iloc[:,:-1]

In [17]:
from sklearn.preprocessing import StandardScaler
absenteesum_scalar=StandardScaler()

In [18]:
absenteesum_scalar.fit(unscaled_inputs)

StandardScaler()

In [19]:
scaled_inputs=absenteesum_scalar.transform(unscaled_inputs)

In [20]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.76743118,
        -0.44798003,  0.88046927],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.44798003, -0.01928035],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.44798003, -0.91902997],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.40857982,
         2.23224237, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
         2.23224237, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
        -0.44798003, -0.01928035]])

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
train_test_split(scaled_inputs,targets)

[array([[-0.57735027, -0.09298136,  3.17979734, ..., -1.34938863,
         -0.44798003,  0.88046927],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.64378202,
         -0.44798003, -0.01928035],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  0.29702678,
         -0.44798003, -0.91902997],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
         -0.44798003, -0.91902997],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.64378202,
         -0.44798003, -0.01928035],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  1.00263338,
         -0.44798003, -0.91902997]]),
 array([[ 1.73205081, -0.09298136, -0.31448545, ..., -1.81979303,
          2.23224237, -0.91902997],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.29702678,
         -0.44798003, -0.91902997],
        [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
         -0.44798003, -0.91902997],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ...,  

In [23]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [24]:
print(x_train.shape,x_test.shape)

(560, 10) (140, 10)


In [25]:
print(y_train.shape,y_test.shape)

(560,) (140,)


In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [27]:
reg = LogisticRegression()

In [28]:
reg.fit(x_train,y_train)

LogisticRegression()

In [29]:
reg.score(x_train,y_train)

0.7767857142857143

In [30]:
model_outputs=reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [31]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [32]:
model_outputs==y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [33]:
np.sum(model_outputs==y_train)

435

In [34]:
model_outputs.shape[0]

560

In [35]:
np.sum(model_outputs==y_train)/model_outputs.shape[0]

0.7767857142857143

In [36]:
reg.intercept_

array([-0.23147481])

In [37]:
reg.coef_

array([[ 2.02646966,  0.32681108,  1.47254365,  1.26132243,  0.01256107,
         0.56710187, -0.13015544,  0.3151747 , -0.10845667,  0.39558049]])

In [38]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children'], dtype=object)

In [39]:
summary_table=pd.DataFrame(columns=['Feature name'],data=unscaled_inputs.columns.values)
summary_table['Coefficient']=np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                Reason_1     2.026470
1                Reason_2     0.326811
2                Reason_3     1.472544
3                Reason_4     1.261322
4             Month Value     0.012561
5  Transportation Expense     0.567102
6                     Age    -0.130155
7         Body Mass Index     0.315175
8               Education    -0.108457
9                Children     0.395580

In [40]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept' ,reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.231475
1                 Reason_1     2.026470
2                 Reason_2     0.326811
3                 Reason_3     1.472544
4                 Reason_4     1.261322
5              Month Value     0.012561
6   Transportation Expense     0.567102
7                      Age    -0.130155
8          Body Mass Index     0.315175
9                Education    -0.108457
10                Children     0.395580

In [41]:
summary_table['Odds_ratio']=np.exp(summary_table.Coefficient)

In [42]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.231475    0.793363
1                 Reason_1     2.026470    7.587253
2                 Reason_2     0.326811    1.386540
3                 Reason_3     1.472544    4.360312
4                 Reason_4     1.261322    3.530087
5              Month Value     0.012561    1.012640
6   Transportation Expense     0.567102    1.763150
7                      Age    -0.130155    0.877959
8          Body Mass Index     0.315175    1.370499
9                Education    -0.108457    0.897218
10                Children     0.395580    1.485246

In [43]:
summary_table.sort_values('Odds_ratio')

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.231475    0.793363
7                      Age    -0.130155    0.877959
9                Education    -0.108457    0.897218
5              Month Value     0.012561    1.012640
8          Body Mass Index     0.315175    1.370499
2                 Reason_2     0.326811    1.386540
10                Children     0.395580    1.485246
6   Transportation Expense     0.567102    1.763150
4                 Reason_4     1.261322    3.530087
3                 Reason_3     1.472544    4.360312
1                 Reason_1     2.026470    7.587253

In [44]:
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler
class Customerscalar(BaseEstimator,TransformerMixin):
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        self.scaler=StandardScalar(copy,with_mean,with_std)
        self.columns=columns
        self.mean_=None
        self.var_=None
    def fit(self,X,y=None):
        self.scaler.fit(X[self.columns],y)
        self.mean_=np.mean(X[self.columns])
        self.var_=np.var(X[self.columns])
        return self
    def transform(self,X,y=None,copy=None):
        init_col_order=X.columns
        X_scaled=pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
        X_notscaled=X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_notscaled,X_scaled],axis=1)[init_col_order]

In [45]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children'], dtype=object)

In [46]:
#colum_to_scale=['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work','Age', 'Daily Work Load Average', 'Body Mass Index', 'Education','Children']

In [47]:
columns_to_omit=['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']
columns_to_scale=[x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [48]:
absenteesum_scalar.fit(unscaled_inputs)

StandardScaler()

In [49]:
scaled_inputs=absenteesum_scalar.transform(unscaled_inputs)

In [50]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.76743118,
        -0.44798003,  0.88046927],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.44798003, -0.01928035],
       [-0.57735027, -0.09298136, -0.31448545, ...,  1.00263338,
        -0.44798003, -0.91902997],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.40857982,
         2.23224237, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
         2.23224237, -0.91902997],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.40857982,
        -0.44798003, -0.01928035]])

In [51]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature name  Coefficient  Odds_ratio
1                 Reason_1     2.026470    7.587253
3                 Reason_3     1.472544    4.360312
4                 Reason_4     1.261322    3.530087
6   Transportation Expense     0.567102    1.763150
10                Children     0.395580    1.485246
2                 Reason_2     0.326811    1.386540
8          Body Mass Index     0.315175    1.370499
5              Month Value     0.012561    1.012640
9                Education    -0.108457    0.897218
7                      Age    -0.130155    0.877959
0                Intercept    -0.231475    0.793363

In [52]:
reg.score(x_test,y_test)

0.7357142857142858

In [53]:
predicted_prob=reg.predict_proba(x_test)
predicted_prob

array([[0.77721435, 0.22278565],
       [0.60455013, 0.39544987],
       [0.49843869, 0.50156131],
       [0.78173949, 0.21826051],
       [0.08224819, 0.91775181],
       [0.303127  , 0.696873  ],
       [0.21378937, 0.78621063],
       [0.07624591, 0.92375409],
       [0.69549248, 0.30450752],
       [0.77916185, 0.22083815],
       [0.36172687, 0.63827313],
       [0.24187359, 0.75812641],
       [0.05383691, 0.94616309],
       [0.70249127, 0.29750873],
       [0.2040476 , 0.7959524 ],
       [0.6224157 , 0.3775843 ],
       [0.36085901, 0.63914099],
       [0.3652073 , 0.6347927 ],
       [0.289175  , 0.710825  ],
       [0.04684019, 0.95315981],
       [0.69229719, 0.30770281],
       [0.78173949, 0.21826051],
       [0.46916802, 0.53083198],
       [0.46542325, 0.53457675],
       [0.14974159, 0.85025841],
       [0.69628838, 0.30371162],
       [0.55785639, 0.44214361],
       [0.90669469, 0.09330531],
       [0.21197732, 0.78802268],
       [0.78173949, 0.21826051],
       [0.

In [54]:
predicted_prob[:,1]

array([0.22278565, 0.39544987, 0.50156131, 0.21826051, 0.91775181,
       0.696873  , 0.78621063, 0.92375409, 0.30450752, 0.22083815,
       0.63827313, 0.75812641, 0.94616309, 0.29750873, 0.7959524 ,
       0.3775843 , 0.63914099, 0.6347927 , 0.710825  , 0.95315981,
       0.30770281, 0.21826051, 0.53083198, 0.53457675, 0.85025841,
       0.30371162, 0.44214361, 0.09330531, 0.78802268, 0.21826051,
       0.39185914, 0.78028288, 0.70240517, 0.64000795, 0.21826051,
       0.60806953, 0.30530459, 0.80982505, 0.48580658, 0.57539613,
       0.2176195 , 0.45495033, 0.30212334, 0.09382972, 0.87296192,
       0.64314423, 0.72627391, 0.21954661, 0.20909131, 0.21697985,
       0.46242059, 0.04494118, 0.696873  , 0.2059986 , 0.84341009,
       0.3972495 , 0.9590266 , 0.24301043, 0.07090144, 0.07114958,
       0.66957504, 0.69925105, 0.24509195, 0.85263683, 0.31195257,
       0.22213513, 0.01106507, 0.30610284, 0.77485008, 0.30066233,
       0.30053978, 0.05650521, 0.89266817, 0.48392786, 0.60447

In [55]:
import pickle

In [56]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [57]:
with open('scaler','wb') as file:
    pickle.dump(absenteesum_scalar,file)